import {FormEvent,useCallback,useEffect,useState} from 'react'
import {Download,FileSpreadsheet,Mail,RefreshCw,Scale,Target,Tags} from 'lucide-react'
import {api,post,patch,receiveServerFile} from '../api/client'
import {Button,Card,Empty,Notice,PageTitle,Status} from '../components/UI'
import {useParams} from 'react-router-dom'

type Tab='documents'|'pricing'|'targets'|'imports'|'approvals'|'email'
const labels:Record<Tab,string>={documents:'Financial Documents',pricing:'Pricing Rules',targets:'Sales Targets',imports:'Catalogue Imports',approvals:'Approvals',email:'Email Delivery'}
const endpoints:Record<Tab,string>={documents:'/api/v1/financial-documents',pricing:'/api/v1/pricing-rules',targets:'/api/v1/sales-targets',imports:'/api/v1/catalogue-imports',approvals:'/api/v1/approval-requests',email:'/api/v1/email-deliveries'}

export default function CommercialOperationsPage(){
  const {workspace='lighting'}=useParams();const ws=workspace.toUpperCase()
  const [tab,setTab]=useState<Tab>('documents'),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
  const [message,setMessage]=useState(''),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const endpoint=tab==='imports'?`${endpoints[tab]}?application=${ws}`:endpoints[tab];const value=await api<any>(endpoint);setRows(Array.isArray(value)?value:value.items||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load data')}finally{setLoading(false)}},[tab,ws])
  useEffect(()=>{load()},[load])
  const value=(form:FormData,key:string)=>String(form.get(key)||'').trim()
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');setMessage('');const form=new FormData(event.currentTarget)
    try{
      if(tab==='documents')await post('/api/v1/financial-documents',{document_type:value(form,'document_type'),customer_id:value(form,'customer_id'),project_id:value(form,'project_id'),order_id:value(form,'order_id')||null,invoice_id:value(form,'invoice_id')||null,reason:value(form,'reason')||null,discount_percent:Number(value(form,'discount')||0),freight:Number(value(form,'freight')||0),additional_charges:0,items:[{product_id:value(form,'product_id')||null,sku:value(form,'sku')||null,description:value(form,'description'),quantity:Number(value(form,'quantity')),unit_price:Number(value(form,'rate')),tax_rate:Number(value(form,'tax_rate'))}]})
      if(tab==='pricing')await post('/api/v1/pricing-rules',{name:value(form,'name'),scope_type:value(form,'scope_type'),product_id:value(form,'product_id')||null,category_id:value(form,'category_id')||null,customer_id:value(form,'customer_id')||null,partner_id:value(form,'partner_id')||null,zone:value(form,'zone')||null,adjustment_type:value(form,'adjustment_type'),adjustment_value:Number(value(form,'adjustment_value')),min_quantity:Number(value(form,'min_quantity')||0),max_quantity:value(form,'max_quantity')?Number(value(form,'max_quantity')):null,valid_from:value(form,'valid_from'),valid_until:value(form,'valid_until')||null,priority:Number(value(form,'priority')||100),status:'ACTIVE'})
      if(tab==='targets')await post('/api/v1/sales-targets',{name:value(form,'name'),target_type:value(form,'target_type'),period_type:value(form,'period_type'),period_start:value(form,'period_start'),period_end:value(form,'period_end'),target_amount:Number(value(form,'target_amount')),sales_user_id:value(form,'sales_user_id')||null,zone:value(form,'zone')||null,partner_id:value(form,'partner_id')||null,status:'ACTIVE'})
      if(tab==='approvals')await post('/api/v1/approval-requests',{entity_type:value(form,'entity_type'),entity_id:value(form,'entity_id'),project_id:value(form,'project_id')||null,rule_code:value(form,'rule_code'),comments:value(form,'comments')||null})
      if(tab==='email')await post('/api/v1/email-deliveries',{template_key:value(form,'template_key'),recipient:value(form,'recipient'),subject:value(form,'subject'),text_body:value(form,'text_body'),html_body:`<p>${escapeHtml(value(form,'text_body'))}</p>`,idempotency_key:value(form,'idempotency_key'),related_type:null,related_id:null})
      event.currentTarget.reset();setMessage(`${labels[tab]} record saved.`);await load()
    }catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget);const mode=value(form,'mode'),dryRun=value(form,'dry_run')==='true'
    try{await api(`/api/v1/catalogue-imports?mode=${mode}&dry_run=${dryRun}&application=${ws}`,{method:'POST',body:form});setMessage(dryRun?'Import validated. No products were changed.':'Import completed.');event.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Import failed')}finally{setSaving(false)}}
  async function action(row:any,action:string){setError('');try{
    if(action==='issue'||action==='cancel')await post(`/api/v1/financial-documents/${row.id}/${action}`)
    if(action==='approve'||action==='reject')await post(`/api/v1/approval-requests/${row.id}/decision`,{decision:action==='approve'?'APPROVED':'REJECTED',comments:null})
    if(action==='retry')await post(`/api/v1/email-deliveries/${row.id}/retry`)
    await load()
  }catch(e){setError(e instanceof Error?e.message:'Action failed')}}
  return <>
    <PageTitle title="Commercial Control" subtitle="Pricing, adjustments, targets, imports, approvals and delivery logs" badge="4.0 workflows" actions={<Button variant="secondary" onClick={load}><RefreshCw size={15}/>Refresh</Button>}/>
    <div className="operations-tabs" role="tablist">{([['documents',Scale],['pricing',Tags],['targets',Target],['imports',FileSpreadsheet],['approvals',Scale],['email',Mail]] as Array<[Tab,typeof Scale]>).map(([key,Icon])=><button key={key} type="button" role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>{setTab(key);setMessage('')}}><Icon size={16}/>{labels[key]}</button>)}</div>
    {error&&<Notice kind="error">{error}</Notice>}{message&&<Notice kind="success">{message}</Notice>}
    <div className="operations-layout with-form"><Card className="table-card"><div className="section-head"><div><h2>{labels[tab]}</h2><p>Authoritative persisted records with role and project scoping.</p></div>{tab==='targets'&&<Button variant="secondary" onClick={()=>receiveServerFile('/api/v1/sales-targets/export.csv','download','sales-targets.csv')}><Download size={15}/>Export CSV</Button>}{tab==='imports'&&<Button variant="secondary" onClick={()=>receiveServerFile('/api/v1/catalogue-import/template.xlsx','download','catalogue-import-template.xlsx')}><Download size={15}/>Template</Button>}</div>
      {loading?<div className="loading">Loading…</div>:rows.length?<div className="table-wrap"><table><thead><tr>{columns(tab).map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||index}>{columns(tab).map(c=><td key={c}>{c==='status'?<Status value={String(row[c])}/>:format(row[c])}</td>)}<td><div className="table-actions">{tab==='documents'&&row.status==='DRAFT'&&<Button variant="secondary" onClick={()=>action(row,'issue')}>Issue</Button>}{tab==='documents'&&row.status!=='CANCELLED'&&<Button variant="danger" onClick={()=>action(row,'cancel')}>Cancel</Button>}{tab==='documents'&&<Button variant="secondary" onClick={()=>receiveServerFile(`/api/v1/financial-documents/${row.id}/pdf`,'preview',`${row.number}.pdf`)}>PDF</Button>}{tab==='imports'&&row.failed_rows>0&&<Button variant="secondary" onClick={()=>receiveServerFile(`/api/v1/catalogue-imports/${row.id}/errors.csv`,'download','import-errors.csv')}>Errors</Button>}{tab==='approvals'&&row.status==='PENDING'&&<><Button variant="secondary" onClick={()=>action(row,'approve')}>Approve</Button><Button variant="danger" onClick={()=>action(row,'reject')}>Reject</Button></>}{tab==='email'&&row.status==='FAILED'&&<Button variant="secondary" onClick={()=>action(row,'retry')}>Retry</Button>}</div></td></tr>)}</tbody></table></div>:<Empty text={`No ${labels[tab].toLowerCase()} yet`}/>}</Card>
      <Card className="operation-form"><h2>{tab==='imports'?'Run catalogue import':`Add ${labels[tab].replace(/s$/,'')}`}</h2><p className="muted">Server validation and audit logging apply to every submission.</p>
        {tab==='imports'?<form onSubmit={upload} className="form-grid"><label>CSV or XLSX *<input type="file" name="file" accept=".csv,.xlsx" required/></label><label>Mode<select name="mode"><option>ATOMIC</option><option>PARTIAL</option></select></label><label>Operation<select name="dry_run"><option value="true">Dry run / validate</option><option value="false">Import products</option></select></label><Button type="submit" disabled={saving}>{saving?'Processing…':'Run import'}</Button></form>:<form onSubmit={submit} className="form-grid">{fields(tab)}<Button type="submit" disabled={saving}>{saving?'Saving…':'Save'}</Button></form>}
      </Card></div>
  </>
}

function fields(tab:Tab){
  if(tab==='documents')return <><label>Type<select name="document_type"><option>PROFORMA</option><option>CREDIT_NOTE</option><option>DEBIT_NOTE</option></select></label><label>Customer ID *<input name="customer_id" required/></label><label>Project ID *<input name="project_id" required/></label><label>Order ID<input name="order_id"/></label><label>Invoice ID<input name="invoice_id"/></label><label>Reason<textarea name="reason"/></label><label>Product ID<input name="product_id"/></label><label>SKU<input name="sku"/></label><label>Description *<input name="description" required/></label><div className="form-grid two"><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Rate<input name="rate" type="number" min="0" step="0.01" required/></label></div><div className="form-grid two"><label>Tax %<input name="tax_rate" type="number" min="0" max="100" defaultValue="18"/></label><label>Discount %<input name="discount" type="number" min="0" max="100" defaultValue="0"/></label></div><label>Freight<input name="freight" type="number" min="0" defaultValue="0"/></label></>
  if(tab==='pricing')return <><label>Name *<input name="name" required/></label><label>Scope<select name="scope_type"><option>GENERAL</option><option>PRODUCT</option><option>CATEGORY</option><option>CUSTOMER</option><option>PARTNER</option><option>ZONE</option></select></label><label>Product ID<input name="product_id"/></label><label>Category ID<input name="category_id"/></label><label>Customer ID<input name="customer_id"/></label><label>Partner ID<input name="partner_id"/></label><label>Zone<input name="zone"/></label><label>Adjustment<select name="adjustment_type"><option>FIXED_PRICE</option><option>PERCENT_DISCOUNT</option><option>FIXED_DISCOUNT</option><option>PERCENT_MARKUP</option></select></label><label>Value *<input name="adjustment_value" type="number" min="0" step="0.01" required/></label><div className="form-grid two"><label>Min qty<input name="min_quantity" type="number" min="0" defaultValue="0"/></label><label>Max qty<input name="max_quantity" type="number" min="0"/></label></div><div className="form-grid two"><label>Valid from<input name="valid_from" type="date" required/></label><label>Valid until<input name="valid_until" type="date"/></label></div><label>Priority<input name="priority" type="number" min="0" defaultValue="100"/></label></>
  if(tab==='targets')return <><label>Name *<input name="name" required/></label><label>Metric<select name="target_type"><option>REVENUE</option><option>ORDERS</option><option>INQUIRIES</option></select></label><label>Period<select name="period_type"><option>MONTHLY</option><option>QUARTERLY</option><option>ANNUAL</option></select></label><div className="form-grid two"><label>Start<input name="period_start" type="date" required/></label><label>End<input name="period_end" type="date" required/></label></div><label>Target amount<input name="target_amount" type="number" min="0" step="0.01" required/></label><label>Sales user ID<input name="sales_user_id"/></label><label>Partner ID<input name="partner_id"/></label><label>Zone<input name="zone"/></label></>
  if(tab==='approvals')return <><label>Entity type<input name="entity_type" required placeholder="QUOTATION"/></label><label>Entity ID<input name="entity_id" required/></label><label>Project ID<input name="project_id"/></label><label>Rule code<input name="rule_code" required placeholder="DISCOUNT_LIMIT"/></label><label>Comments<textarea name="comments"/></label></>
  return <><label>Template key<input name="template_key" required placeholder="quotation-issued"/></label><label>Recipient<input name="recipient" type="email" required/></label><label>Subject<input name="subject" required/></label><label>Message<textarea name="text_body" required/></label><label>Idempotency key<input name="idempotency_key" required placeholder="event-entity-version"/></label></>
}
function columns(tab:Tab){return ({documents:['number','document_type','status','grand_total','created_at'],pricing:['name','scope_type','adjustment_type','adjustment_value','priority','status'],targets:['name','target_type','target_amount','actual','achievement_percent','status'],imports:['file_name','mode','dry_run','success_rows','failed_rows','status'],approvals:['entity_type','rule_code','requested_by','status','created_at'],email:['template_key','recipient','attempts','status','sent_at']} as Record<Tab,string[]>)[tab]}
function format(value:unknown){if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='number')return new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(value);return String(value).replaceAll('_',' ')}
function escapeHtml(value:string){return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]||char))}
