import {useEffect,useState} from 'react'
import {Download} from 'lucide-react'
import {useNavigate,useParams} from 'react-router-dom'
import {api,receiveServerFile} from '../api/client'
import {Breadcrumbs,Button,Card,Empty,Notice,PageTitle,Status} from '../components/UI'
import type {MainBoard} from '../types'

type FloorData={project_id:string;building:{id:string;name:string};floor:{id:string;name:string;sort_order:number;status:string};rooms:Array<{id:string;name:string;room_type?:string|null;area?:number|null;occupancy?:number|null;notes?:string|null;status:string}>;main_boards:MainBoard[];product_summary:{unique_products:number;total_quantity:number}}

export default function FloorDetailPage(){const {workspace='lighting',customerId,id:projectId,buildingId,floorId}=useParams();const navigate=useNavigate();const [data,setData]=useState<FloorData>(),[error,setError]=useState<string>();useEffect(()=>{api<FloorData>(`/api/v1/projects/${projectId}/buildings/${buildingId}/floors/${floorId}`).then(setData).catch(e=>setError(e.message))},[projectId,buildingId,floorId]);if(!data)return <div className="loading">Loading floor…</div>;const base=customerId?`/app/${workspace}/customers/${customerId}/projects/${projectId}`:`/app/${workspace}/projects/${projectId}`;return <><Breadcrumbs items={[{label:'Project',to:base},{label:data.building.name,to:`${base}/buildings/${buildingId}`},{label:data.floor.name}]}/><PageTitle title={data.floor.name} subtitle={`${data.building.name} · Floor ${data.floor.sort_order+1}`} badge={data.floor.status} actions={<Button variant="secondary" onClick={()=>receiveServerFile(`/api/v1/projects/${projectId}/buildings/${buildingId}/floors/${floorId}/sheet.pdf?workspace=${workspace.toUpperCase()}`,'download').catch(e=>setError(e.message))}><Download size={16}/> Floor Sheet</Button>}/>{error&&<Notice kind="error">{error}</Notice>}<div className="detail-kpis"><Card><small>Rooms</small><h3>{data.rooms.length}</h3></Card><Card><small>Main boards</small><h3>{data.main_boards.reduce((sum,x)=>sum+x.quantity,0)}</h3></Card><Card><small>Unique products</small><h3>{data.product_summary.unique_products}</h3></Card><Card><small>Total quantity</small><h3>{data.product_summary.total_quantity}</h3></Card></div><Card><h2>Rooms</h2>{!data.rooms.length?<Empty text="No active rooms on this floor."/>:<div className="building-room-grid">{data.rooms.map(room=><button className="building-room-card" type="button" key={room.id} onClick={()=>navigate(`${base}/buildings/${buildingId}/floors/${floorId}/rooms/${room.id}`)}><div className="room-card-title"><span><b>{room.name}</b><small>{room.room_type||'Room'}</small></span><Status value={room.status}/></div><div className="room-card-meta"><span>{room.area??'—'}<small>Area m²</small></span><span>{room.occupancy??'—'}<small>Occupancy</small></span></div></button>)}</div>}</Card><Card><h2>Main boards</h2>{!data.main_boards.length?<Empty text="No active main boards on this floor."/>:<div className="compact-list">{data.main_boards.map(board=><div key={board.id}><span><b>{board.name}</b><small>{board.code||'No code'} · {board.board_type} · {board.system}</small></span><strong>× {board.quantity}</strong></div>)}</div>}</Card></>}
