import {FormEvent,useCallback,useEffect,useState} from 'react'
import {Bell,Building2,Headphones,Library,PackageCheck,RefreshCw,Truck} from 'lucide-react'
import {api,post,receiveServerFile} from '../api/client'
import {Button,Card,Empty,Notice,PageTitle,StatCard,Status} from '../components/UI'

type Tab='partners'|'warehouses'|'inventory'|'dispatch'|'rma'|'announcements'|'tickets'|'resources'
type Dashboard={partners:number;pending_approvals:number;open_dispatches:number;open_rmas:number;open_tickets:number;unread_notifications:number}
const endpoints:Record<Tab,string>={partners:'/api/v1/partners',warehouses:'/api/v1/warehouses',inventory:'/api/v1/stock/balances',dispatch:'/api/v1/dispatches',rma:'/api/v1/rmas',announcements:'/api/v1/announcements',tickets:'/api/v1/tickets',resources:'/api/v1/resources'}
const labels:Record<Tab,string>={partners:'Partners',warehouses:'Warehouses',inventory:'Inventory',dispatch:'Dispatch',rma:'RMA & Service',announcements:'Announcements',tickets:'Support',resources:'Resources'}

export default function OperationsPage(){
  const [tab,setTab]=useState<Tab>('partners'),[stats,setStats]=useState<Dashboard>(),[rows,setRows]=useState<any[]>([])
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [dashboard,data]=await Promise.all([api<Dashboard>('/api/v1/operations/dashboard'),api<any[]>(endpoints[tab])]);setStats(dashboard);setRows(data)}catch(e){setError(e instanceof Error?e.message:'Unable to load operations')}finally{setLoading(false)}},[tab])
  useEffect(()=>{load()},[load])
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setSaving(true);setError('');setMessage('')
    const form=new FormData(event.currentTarget),value=(key:string)=>String(form.get(key)||'').trim()
    try{
      if(tab==='partners')await post('/api/v1/partners',{business_name:value('name'),partner_type:value('type'),mobile:value('phone'),email:value('email'),address:value('address'),credit_terms_days:Number(value('credit_terms')||0),credit_limit:Number(value('credit_limit')||0)})
      else if(tab==='warehouses')await post('/api/v1/warehouses',{code:value('code'),name:value('name'),address:value('address')||null,partner_id:value('partner_id')||null,allow_negative:value('allow_negative')==='true'})
      else if(tab==='inventory')await post('/api/v1/stock/movements',{warehouse_id:value('warehouse_id'),product_id:value('product_id'),movement_type:value('movement_type'),quantity:Number(value('quantity')),direction:value('direction'),reference_type:value('reference_type')||null,reference_id:value('reference_id')||null,idempotency_key:value('idempotency_key'),notes:value('notes')||null})
      else if(tab==='dispatch')await post('/api/v1/dispatches',{order_id:value('order_id'),warehouse_id:value('warehouse_id')||null,delivery_address:value('delivery_address'),transporter:value('transporter')||null,vehicle_number:value('vehicle_number')||null,tracking_number:value('tracking_number')||null,expected_delivery:value('expected_delivery')||null,items:[{order_item_id:value('order_item_id'),quantity:Number(value('quantity'))}]})
      else if(tab==='rma')await post('/api/v1/rmas',{customer_id:value('customer_id'),project_id:value('project_id')||null,order_id:value('order_id')||null,invoice_id:value('invoice_id')||null,product_id:value('product_id'),serial_number:value('serial_number')||null,quantity:Number(value('quantity')),reason:value('reason'),description:value('description')})
      else if(tab==='tickets')await post('/api/v1/tickets',{category:value('category'),subject:value('subject'),description:value('description'),priority:value('priority')})
      else if(tab==='announcements')await post('/api/v1/announcements',{title:value('title'),content:value('content'),priority:value('priority'),status:'PUBLISHED',audience:{all:true}})
      else if(tab==='resources')await post('/api/v1/resources',{title:value('title'),resource_type:value('type'),workspace:value('workspace')||null,url:value('url'),description:value('description'),audience:{all:true}})
      else return
      event.currentTarget.reset();setMessage(labels[tab]+' record saved.');await load()
    }catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}
  }
  async function advance(row:any){setError('');try{let target='';const dispatchNext:Record<string,string>={DRAFT:'READY',READY:'DISPATCHED',DISPATCHED:'DELIVERED'};const rmaNext:Record<string,string>={REQUESTED:'APPROVED',APPROVED:'RECEIVED',PICKUP_SCHEDULED:'RECEIVED',RECEIVED:'INSPECTING',INSPECTING:'REPAIR',REPAIR:'RESOLVED',REPLACE:'RESOLVED',REFUND:'RESOLVED',RESOLVED:'CLOSED',REJECTED:'CLOSED'};if(tab==='partners')target=row.status==='PENDING'?'ACTIVE':row.status==='ACTIVE'?'INACTIVE':'ACTIVE';if(tab==='dispatch')target=dispatchNext[String(row.status)]||'';if(tab==='rma')target=rmaNext[String(row.status)]||'';if(!target)return;await post(`/api/v1/${tab==='partners'?'partners':tab==='dispatch'?'dispatches':'rmas'}/${row.id}/status`,{status:target,notes:null,reason:null});await load()}catch(e){setError(e instanceof Error?e.message:'Status update failed')}}
  async function assess(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),v=(key:string)=>String(form.get(key)||'').trim();setSaving(true);try{await api(`/api/v1/rmas/${v('rma_id')}/assessment`,{method:'PATCH',body:JSON.stringify({warranty_eligible:v('warranty_eligible')===''?null:v('warranty_eligible')==='true',warranty_reason:v('warranty_reason')||null,inspection_notes:v('inspection_notes')||null,diagnosis:v('diagnosis')||null,customer_notes:v('customer_notes')||null,internal_notes:v('internal_notes')||null,labour_cost:Number(v('labour_cost')||0),sla_due_at:v('sla_due_at')||null,pickup_reference:v('pickup_reference')||null,return_dispatch_reference:v('return_dispatch_reference')||null})});setMessage('RMA assessment saved.')}catch(e){setError(e instanceof Error?e.message:'Assessment failed')}finally{setSaving(false)}}
  async function addPart(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),v=(key:string)=>String(form.get(key)||'').trim();setSaving(true);try{await post(`/api/v1/rmas/${v('rma_id')}/parts`,{product_id:v('product_id'),warehouse_id:v('warehouse_id'),quantity:Number(v('quantity')),unit_cost:Number(v('unit_cost')||0)});setMessage('RMA part and stock movement saved.')}catch(e){setError(e instanceof Error?e.message:'Part issue failed')}finally{setSaving(false)}}
  async function evidence(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),id=String(form.get('rma_id')||'');setSaving(true);try{form.delete('rma_id');await api(`/api/v1/rmas/${id}/evidence`,{method:'POST',body:form});setMessage('Evidence uploaded.')}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setSaving(false)}}
  const canCreate=true
  return <>
    <PageTitle title="Operations Centre" subtitle="Partners, stock, dispatch, service, communications and controlled resources" badge="Live data" actions={<Button variant="secondary" onClick={load}><RefreshCw size={15}/>Refresh</Button>}/>
    {stats&&<div className="stats-grid operations-stats"><StatCard label="Active Partners" value={stats.partners}/><StatCard label="Open Dispatches" value={stats.open_dispatches} kind="orange"/><StatCard label="Open RMAs" value={stats.open_rmas} kind="purple"/><StatCard label="Open Tickets" value={stats.open_tickets} kind="green"/></div>}
    <div className="operations-tabs" role="tablist">{([['partners',Building2],['warehouses',Building2],['inventory',PackageCheck],['dispatch',Truck],['rma',RefreshCw],['announcements',Bell],['tickets',Headphones],['resources',Library]] as Array<[Tab,typeof Building2]>).map(([key,Icon])=><button key={key} type="button" role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>{setTab(key);setMessage('')}}><Icon size={16}/>{labels[key]}</button>)}</div>
    {error&&<Notice kind="error">{error}</Notice>}{message&&<Notice kind="success">{message}</Notice>}
    <div className={'operations-layout '+(canCreate?'with-form':'')}>
      <Card className="table-card"><div className="section-head"><div><h2>{labels[tab]}</h2><p>Persisted records filtered by your role and scope.</p></div></div>
        {loading?<div className="loading">Loading {labels[tab].toLowerCase()}…</div>:rows.length?<div className="table-wrap"><table><thead><tr>{columns(tab).map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||tab+'-'+index}>{columns(tab).map(column=><td key={column}>{column==='status'?<Status value={String(row[column]||'ACTIVE')}/>:format(row[column])}</td>)}<td><div className="table-actions">{['partners','dispatch','rma'].includes(tab)&&<Button variant="secondary" onClick={()=>advance(row)}>Advance</Button>}{tab==='rma'&&<Button variant="secondary" onClick={()=>receiveServerFile(`/api/v1/rmas/${row.id}/service-report.pdf`,'preview',`${row.number}-service-report.pdf`)}>Report</Button>}</div></td></tr>)}</tbody></table></div>:<Empty text={'No '+labels[tab].toLowerCase()+' records yet'}/>} 
      </Card>
      {canCreate&&<Card className="operation-form"><h2>Add {labels[tab].replace(/s$/,'')}</h2><p className="muted">Required information is validated and saved by the server.</p>
        <form onSubmit={submit} className="form-grid">
          {tab==='partners'&&<><label>Business name *<input name="name" required minLength={2}/></label><label>Partner type *<select name="type" required><option>DEALER</option><option>DISTRIBUTOR</option><option>SYSTEM_INTEGRATOR</option><option>ARCHITECT_CONSULTANT</option><option>CONTRACTOR</option><option>RESELLER</option><option>OTHER</option></select></label><label>Email *<input name="email" type="email" required/></label><label>Phone *<input name="phone" required minLength={6}/></label><label>Address *<textarea name="address" required/></label><div className="form-grid two"><label>Credit days<input name="credit_terms" type="number" min="0" max="365" defaultValue="0"/></label><label>Credit limit<input name="credit_limit" type="number" min="0" step="0.01" defaultValue="0"/></label></div></>}
          {tab==='warehouses'&&<><label>Code *<input name="code" required/></label><label>Name *<input name="name" required/></label><label>Partner ID<input name="partner_id"/></label><label>Address<textarea name="address"/></label><label>Negative stock<select name="allow_negative"><option value="false">Disallow</option><option value="true">Allow</option></select></label></>}
          {tab==='inventory'&&<><label>Warehouse ID *<input name="warehouse_id" required/></label><label>Product ID *<input name="product_id" required/></label><label>Direction<select name="direction"><option>IN</option><option>OUT</option></select></label><label>Movement type<select name="movement_type"><option>RECEIPT</option><option>TRANSFER</option><option>ADJUSTMENT</option><option>RETURN</option></select></label><label>Quantity *<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Idempotency key *<input name="idempotency_key" required/></label><label>Reference type<input name="reference_type"/></label><label>Reference ID<input name="reference_id"/></label><label>Notes<textarea name="notes"/></label></>}
          {tab==='dispatch'&&<><label>Order ID *<input name="order_id" required/></label><label>Order item ID *<input name="order_item_id" required/></label><label>Quantity *<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Warehouse ID<input name="warehouse_id"/></label><label>Delivery address *<textarea name="delivery_address" required/></label><label>Transporter<input name="transporter"/></label><label>Vehicle number<input name="vehicle_number"/></label><label>Tracking number<input name="tracking_number"/></label><label>Expected delivery<input name="expected_delivery" type="date"/></label></>}
          {tab==='rma'&&<><label>Customer ID *<input name="customer_id" required/></label><label>Project ID<input name="project_id"/></label><label>Order ID<input name="order_id"/></label><label>Invoice ID<input name="invoice_id"/></label><label>Product ID *<input name="product_id" required/></label><label>Serial number<input name="serial_number"/></label><label>Quantity *<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Reason *<input name="reason" required/></label><label>Description *<textarea name="description" required minLength={5}/></label></>}
          {tab==='tickets'&&<><label>Category *<select name="category"><option>PRODUCT</option><option>DELIVERY</option><option>PAYMENT</option><option>TECHNICAL</option><option>OTHER</option></select></label><label>Subject *<input name="subject" required minLength={2}/></label><label>Description *<textarea name="description" required minLength={5}/></label><label>Priority<select name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label></>}
          {tab==='announcements'&&<><label>Title *<input name="title" required minLength={2}/></label><label>Content *<textarea name="content" required minLength={2}/></label><label>Priority<select name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label></>}
          {tab==='resources'&&<><label>Title *<input name="title" required minLength={2}/></label><label>Type *<select name="type"><option>BROCHURE</option><option>CATALOGUE</option><option>MANUAL</option><option>TRAINING</option><option>POLICY</option><option>VIDEO</option></select></label><label>Workspace<select name="workspace"><option value="">All</option><option>LIGHTING</option><option>AUTOMATION</option></select></label><label>Secure URL *<input name="url" type="url" required placeholder="https://…"/></label><label>Description<textarea name="description"/></label></>}
          <Button type="submit" disabled={saving}>{saving?'Saving…':'Save record'}</Button>
        </form>
        {tab==='rma'&&<div className="service-tools"><hr/><h3>Service assessment</h3><form onSubmit={assess} className="form-grid"><label>RMA ID *<input name="rma_id" required/></label><label>Warranty eligibility<select name="warranty_eligible"><option value="">Pending</option><option value="true">Eligible</option><option value="false">Not eligible</option></select></label><label>Warranty reason<textarea name="warranty_reason"/></label><label>Inspection notes<textarea name="inspection_notes"/></label><label>Diagnosis<textarea name="diagnosis"/></label><label>Customer notes<textarea name="customer_notes"/></label><label>Internal notes<textarea name="internal_notes"/></label><label>Labour cost<input name="labour_cost" type="number" min="0" step="0.01" defaultValue="0"/></label><label>SLA due<input name="sla_due_at" type="datetime-local"/></label><label>Pickup reference<input name="pickup_reference"/></label><label>Return dispatch reference<input name="return_dispatch_reference"/></label><Button type="submit" disabled={saving}>Save assessment</Button></form><h3>Consume service part</h3><form onSubmit={addPart} className="form-grid"><label>RMA ID *<input name="rma_id" required/></label><label>Part product ID *<input name="product_id" required/></label><label>Warehouse ID *<input name="warehouse_id" required/></label><label>Quantity *<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Unit cost<input name="unit_cost" type="number" min="0" step="0.01"/></label><Button type="submit" disabled={saving}>Issue part</Button></form><h3>Evidence</h3><form onSubmit={evidence} className="form-grid"><label>RMA ID *<input name="rma_id" required/></label><label>PDF, PNG or JPEG *<input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required/></label><Button type="submit" disabled={saving}>Upload evidence</Button></form></div>}
      </Card>}
    </div>
  </>
}
function columns(tab:Tab){return ({partners:['business_name','partner_type','zone','credit_limit','status'],warehouses:['code','name','partner_id','allow_negative','status'],inventory:['warehouse','sku','product','balance','low_stock'],dispatch:['number','order_id','transporter','tracking_number','status'],rma:['number','reason','serial_number','quantity','status'],announcements:['title','priority','starts_at','ends_at','status'],tickets:['number','category','subject','priority','status'],resources:['title','type','workspace','url']} as Record<Tab,string[]>)[tab]}
function format(value:unknown){if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='number')return new Intl.NumberFormat('en-IN').format(value);const text=String(value);return text.startsWith('http')?<a href={text} target="_blank" rel="noopener noreferrer">Open</a>:text.replaceAll('_',' ')}
