import {useEffect,useMemo,useState} from 'react'
import type {ReactNode} from 'react'
import {useNavigate,useParams,useSearchParams} from 'react-router-dom'
import {ArrowUpRight,Building2,ChevronDown,ChevronRight,Download,Eye,FileSpreadsheet,MapPin,Plus,Settings,Trash2} from 'lucide-react'
import {api,del,downloadInvoice,downloadQuotation,post,projectBookPath,receiveServerFile} from '../api/client'
import type {BOQRow,ProjectDetail,ProjectUser} from '../types'
import {Breadcrumbs,Button,Card,Empty,Modal,Notice,PageTitle,Status,money} from '../components/UI'
import {useAuth} from '../app/AuthContext'

type Tab='overview'|'buildings'|'products'|'inquiries'|'quotations'|'orders'|'invoices'|'documents'
const tabs:Tab[]=['overview','buildings','products','inquiries','quotations','orders','invoices','documents']

function projectBoq(data:ProjectDetail):BOQRow[]{
  const rows=new Map<string,BOQRow>()
  for(const building of data.buildings)for(const floor of building.floors)for(const room of floor.rooms)for(const item of room.requirements){
    const product=item.product
    const current=rows.get(product.id)||{product_id:product.id,sku:product.sku,name:product.name,category:product.category,workspace:product.workspace,unit:item.unit||product.unit,quantity:0,rate:product.price,tax_rate:product.tax_rate,specs:product.specs||{},breakdown:[]}
    current.quantity+=Number(item.quantity)
    current.breakdown.push({building:building.name,floor:floor.name,room:room.name,quantity:Number(item.quantity),notes:item.notes})
    rows.set(product.id,current)
  }
  return [...rows.values()].sort((a,b)=>a.name.localeCompare(b.name))
}

export default function ProjectDetailPage(){
  const {id,customerId,workspace='lighting'}=useParams();const {user}=useAuth();const navigate=useNavigate();const [params,setParams]=useSearchParams()
  const tab=(tabs.includes(params.get('tab') as Tab)?params.get('tab'):'overview') as Tab
  const [data,setData]=useState<ProjectDetail>();const [notice,setNotice]=useState<{kind:'success'|'warning'|'error';text:string}>();const [busy,setBusy]=useState<string>()
  const [userModal,setUserModal]=useState(false);const [removeUser,setRemoveUser]=useState<ProjectUser>();const [form,setForm]=useState({name:'',email:'',phone:''})
  const [buildingFilter,setBuildingFilter]=useState('all');const [floorFilter,setFloorFilter]=useState('all');const [roomFilter,setRoomFilter]=useState('all');const [systemFilter,setSystemFilter]=useState(workspace.toUpperCase());const [query,setQuery]=useState('');const [expanded,setExpanded]=useState<Record<string,boolean>>({})
  const load=()=>api<ProjectDetail>(`/api/v1/projects/${id}?workspace=${workspace.toUpperCase()}`).then(setData).catch(reason=>setNotice({kind:'error',text:reason.message}))
  useEffect(()=>{void load()},[id,workspace])
  const allBoq=useMemo(()=>data?projectBoq(data):[],[data])
  const filteredBoq=useMemo(()=>allBoq.map(row=>({...row,breakdown:row.breakdown.filter(item=>(buildingFilter==='all'||item.building===buildingFilter)&&(floorFilter==='all'||item.floor===floorFilter)&&(roomFilter==='all'||item.room===roomFilter))})).filter(row=>row.breakdown.length&&(systemFilter==='all'||row.workspace===systemFilter)&&(`${row.name} ${row.sku} ${row.category}`.toLowerCase().includes(query.toLowerCase()))).map(row=>({...row,quantity:row.breakdown.reduce((sum,item)=>sum+Number(item.quantity),0)})),[allBoq,buildingFilter,floorFilter,roomFilter,systemFilter,query])
  if(!data)return <Card>{notice&&<Notice kind="error">{notice.text}</Notice>}<div className="loading">Loading project workspace…</div><Button onClick={load}>Retry</Button></Card>
  const p=data.project;const cid=customerId||data.customer.id;const base=`/app/${workspace}/customers/${cid}/projects/${id}`
  const scope=(buildingId?:string|null)=>data.buildings.find(item=>item.id===buildingId)?.name||'Project-wide'
  const runFile=async(key:string,path:string,mode:'preview'|'download')=>{const scoped=`${path}${path.includes('?')?'&':'?'}workspace=${workspace.toUpperCase()}`;setBusy(key);try{await receiveServerFile(scoped,mode)}catch(reason){setNotice({kind:'error',text:reason instanceof Error?reason.message:'Report generation failed.'})}finally{setBusy(undefined)}}
  const mutate=async(key:string,path:string,success:string,confirmText?:string,body?:unknown)=>{if(confirmText&&!window.confirm(confirmText))return;setBusy(key);setNotice(undefined);try{const result=await post<{id?:string}>(path,body);setNotice({kind:'success',text:success});await load();return result}catch(reason){setNotice({kind:'error',text:reason instanceof Error?reason.message:'Action failed.'})}finally{setBusy(undefined)}}
  const addUser=async()=>{setBusy('user');try{const created=await post<ProjectUser>(`/api/v1/projects/${id}/users`,form);setNotice({kind:created.temporary_password?'warning':'success',text:created.temporary_password?`User assigned. One-time temporary password: ${created.temporary_password}`:'User assigned to this project.'});setUserModal(false);setForm({name:'',email:'',phone:''});load()}catch(reason){setNotice({kind:'error',text:reason instanceof Error?reason.message:'User assignment failed.'})}finally{setBusy(undefined)}}
  const remove=async()=>{if(!removeUser)return;setBusy('remove');try{await del(`/api/v1/projects/${id}/users/${removeUser.user_id}`);setRemoveUser(undefined);load()}catch(reason){setNotice({kind:'error',text:reason instanceof Error?reason.message:'Could not remove user.'})}finally{setBusy(undefined)}}
  const latestInquiry=data.inquiries[0];const latestQuote=data.quotations[0];const latestOrder=data.orders[0];const latestInvoice=data.invoices[0]
  const workflow=[['Inquiry',latestInquiry?.status||'NOT_STARTED'],['BOQ',allBoq.length?'READY':'NOT_STARTED'],['Quotation',latestQuote?.status||'NOT_STARTED'],['Order',latestOrder?.status||'NOT_STARTED'],['Invoice',latestInvoice?.status||'NOT_STARTED']]
  const floors=[...new Set(data.buildings.flatMap(b=>b.floors.map(f=>f.name)))];const rooms=[...new Set(data.buildings.flatMap(b=>b.floors.flatMap(f=>f.rooms.map(r=>r.name))))]
  return <>
    <Breadcrumbs items={[{label:'Customers',to:`/app/${workspace}/customers`},{label:data.customer.company_name,to:`/app/${workspace}/customers/${cid}`},{label:p.name}]}/>
    <PageTitle title={p.name} subtitle={`${data.customer.company_name} · ${[p.address,p.city,p.state].filter(Boolean).join(', ')||'Site location not provided'}`} badge={(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')?'Admin':'My Project'} actions={<><Button variant="secondary" disabled={Boolean(busy)} onClick={()=>runFile('project-preview',projectBookPath(id!),'preview')}><Eye size={16}/>{busy==='project-preview'?'Preparing…':'Preview Project Book'}</Button><Button variant="secondary" disabled={Boolean(busy)} onClick={()=>runFile('project-download',projectBookPath(id!,true),'download')}><Download size={16}/>{busy==='project-download'?'Preparing…':'Download Project Book'}</Button>{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&<Button onClick={()=>navigate(`/app/${workspace}/inquiries/new?project_id=${id}`)}><Plus size={16}/> Create Inquiry</Button>}{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&<Button variant="secondary" onClick={()=>setUserModal(true)}><Settings size={16}/> Project Access</Button>}</>}/>
    {notice&&<Notice kind={notice.kind}>{notice.text}</Notice>}
    <div className="detail-kpis three"><Card><small>Buildings</small><h3>{data.stats.buildings||data.buildings.length}</h3></Card><Card><small>Floors</small><h3>{data.stats.floors}</h3></Card><Card><small>Rooms</small><h3>{data.stats.rooms}</h3></Card></div>
    <div className="detail-tabs" role="tablist" aria-label="Project sections">{tabs.map(value=><button type="button" role="tab" aria-selected={tab===value} key={value} className={tab===value?'active':''} onClick={()=>setParams({tab:value})}>{value==='buildings'?'Buildings & Floors':value==='products'?'Products / BOQ':value[0].toUpperCase()+value.slice(1)}</button>)}</div>

    {tab==='overview'&&<><div className="project-overview-grid"><Card><h3>Project Overview</h3><dl className="info-list"><div><dt>Customer</dt><dd>{data.customer.company_name}</dd></div><div><dt>Project</dt><dd>{p.name}</dd></div><div><dt>Site address</dt><dd>{[p.address,p.city,p.state].filter(Boolean).join(', ')||'—'}</dd></div><div><dt>Status</dt><dd><Status value={p.status}/></dd></div><div><dt>Scope</dt><dd>{p.workspaces.join(' · ')}</dd></div></dl></Card><Card><h3>Ownership</h3><dl className="info-list"><div><dt>Internal owner</dt><dd>{p.owner?.name||'Not assigned'}</dd></div><div><dt>Partner</dt><dd>{data.partner?.business_name||'No partner'}</dd></div><div><dt>Created</dt><dd>{p.created_at?new Date(p.created_at).toLocaleDateString():'—'}</dd></div><div><dt>Updated</dt><dd>{p.updated_at?new Date(p.updated_at).toLocaleString():'—'}</dd></div></dl></Card></div><Card className="workflow-card"><div className="section-head"><div><h2>Commercial Progress</h2><p>Stages reflect persisted records; no downstream document is assumed.</p></div></div><div className="workflow-tracker">{workflow.map(([label,status],index)=><div className="workflow-stage" key={label}><span>{index+1}</span><div><b>{label}</b><Status value={status}/></div></div>)}</div></Card><Card><h2>Recent Activity</h2>{!data.activity?.length?<Empty text="No project activity has been recorded."/>:<div className="activity-timeline">{data.activity.slice(0,10).map(item=><div key={item.id}><span><b>{item.action.replaceAll('.',' · ').replaceAll('_',' ')}</b><small>{item.actor} · {new Date(item.created_at).toLocaleString()}</small></span></div>)}</div>}</Card></>}

    {tab==='buildings'&&(!data.buildings.length?<Card><Empty text="No buildings have been configured. Create an inquiry to define the physical structure." action={(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')?<Button onClick={()=>navigate(`/app/${workspace}/inquiries/new?project_id=${id}`)}>Create Inquiry</Button>:undefined}/></Card>:<div className="building-card-grid">{data.buildings.map(building=><article className="building-card" key={building.id}><div className="building-card-head"><span><Building2 size={22}/></span><div><h2>{building.name}</h2><p>{building.code||'No building code'}</p></div><Status value={building.status||'ACTIVE'}/></div><p className="project-location"><MapPin size={15}/>{building.address||p.address||'Site location not provided'}</p><div className="building-card-stats building-card-stats-compact"><span><b>{building.floor_count}</b><small>Floors</small></span><span><b>{building.room_count||0}</b><small>Rooms</small></span><span><b>{building.main_board_count||0}</b><small>Main boards</small></span></div><div className="project-card-actions"><Button onClick={()=>navigate(`${base}/buildings/${building.id}`)}>Open Building <ArrowUpRight size={15}/></Button></div></article>)}</div>)}

    {tab==='products'&&<Card className="table-card"><div className="section-head"><div><h2>Project Products / BOQ</h2><p>Aggregated from persisted room-level requirements across every building.</p></div><div className="button-row"><Button variant="secondary" onClick={()=>runFile('book',`/api/v1/projects/${id}/book.pdf`,'preview')}><Eye size={15}/> Preview Project Book</Button><Button onClick={()=>runFile('project-boq',`/api/v1/projects/${id}/boq.xlsx`,'download')}><FileSpreadsheet size={15}/> Export Project BOQ</Button>{buildingFilter!=='all'&&<Button onClick={()=>runFile('boq',`/api/v1/projects/${id}/buildings/${data.buildings.find(b=>b.name===buildingFilter)?.id}/boq.xlsx`,'download')}><FileSpreadsheet size={15}/> Export Building BOQ</Button>}</div></div><div className="boq-callout"><span><b>{filteredBoq.length}</b><small>Unique products</small></span><span><b>{filteredBoq.reduce((sum,row)=>sum+row.quantity,0)}</b><small>Total quantity</small></span></div><div className="boq-filters"><select aria-label="Building filter" value={buildingFilter} onChange={event=>setBuildingFilter(event.target.value)}><option value="all">All Buildings</option>{data.buildings.map(b=><option key={b.id}>{b.name}</option>)}</select><select aria-label="Floor filter" value={floorFilter} onChange={event=>setFloorFilter(event.target.value)}><option value="all">All Floors</option>{floors.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Room filter" value={roomFilter} onChange={event=>setRoomFilter(event.target.value)}><option value="all">All Rooms</option>{rooms.map(value=><option key={value}>{value}</option>)}</select><select aria-label="System filter" value={systemFilter} onChange={event=>setSystemFilter(event.target.value)}><option value="LIGHTING">Lighting</option><option value="AUTOMATION">Automation</option></select><input aria-label="Product search" placeholder="Search product, SKU or category" value={query} onChange={event=>setQuery(event.target.value)}/></div>{!filteredBoq.length?<Empty text="No room products match these filters. Add products through the inquiry wizard or room configuration."/>:<div className="table-wrap"><table><thead><tr><th></th><th>Product</th><th>SKU</th><th>System</th><th>Category</th><th>Unit</th>{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&<><th>Rate</th><th>Tax</th></>}<th>Quantity</th></tr></thead><tbody>{filteredBoq.map(row=><ProjectBoqRow key={row.product_id} row={row} showPrices={(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')} open={Boolean(expanded[row.product_id])} toggle={()=>setExpanded(value=>({...value,[row.product_id]:!value[row.product_id]}))}/>)}</tbody></table></div>}</Card>}

    {tab==='inquiries'&&<CommercialCard title="Inquiries" empty={!data.inquiries.length?{text:'No inquiry has been submitted for this project. Start an inquiry to define rooms and product requirements.',action:(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')?<Button onClick={()=>navigate(`/app/${workspace}/inquiries/new?project_id=${id}`)}>Create Inquiry</Button>:undefined}:undefined}><table><thead><tr><th>Inquiry</th><th>Building scope</th><th>Created</th><th>Status</th><th>Owner</th><th>Estimated value</th><th>Action</th></tr></thead><tbody>{data.inquiries.map(item=><tr key={item.id}><td>{item.number}</td><td>{scope(item.building_id)}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td><Status value={item.status}/></td><td>{item.owner.name}</td><td>{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')?money(item.estimated_value):'Restricted'}</td><td><div className="button-row"><Button variant="secondary" onClick={()=>navigate(`/app/${workspace}/inquiries/${item.id}`)}>Open</Button>{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&!data.quotations.some(q=>q.inquiry_id===item.id)&&<Button disabled={Boolean(busy)} onClick={()=>mutate(`quote-${item.id}`,`/api/v1/inquiries/${item.id}/quotation`,'Draft quotation generated.','Generate a draft quotation from the current BOQ?')}>Generate Quotation</Button>}</div></td></tr>)}</tbody></table></CommercialCard>}

    {tab==='quotations'&&<CommercialCard title="Quotations" empty={!data.quotations.length?{text:`No quotation has been generated yet. The BOQ is ready with ${allBoq.length} products and ${allBoq.reduce((sum,row)=>sum+row.quantity,0)} units.`,action:(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&latestInquiry?<Button disabled={Boolean(busy)} onClick={()=>mutate('quote',`/api/v1/inquiries/${latestInquiry.id}/quotation`,'Draft quotation generated.','Generate a draft quotation from the latest inquiry BOQ?')}>Generate Draft Quotation</Button>:undefined}:undefined}><table><thead><tr><th>Quotation</th><th>Inquiry</th><th>Building scope</th><th>Date</th><th>Revision</th><th>Status</th><th>Valid until</th><th>Total</th><th>Action</th></tr></thead><tbody>{data.quotations.map(item=><tr key={item.id}><td>{item.number}</td><td>{data.inquiries.find(x=>x.id===item.inquiry_id)?.number||'—'}</td><td>{scope(item.building_id)}</td><td>{item.quotation_date}</td><td>{item.revision||1}</td><td><Status value={item.status}/></td><td>{item.valid_until||'—'}</td><td>{money(item.grand_total)}</td><td><div className="button-row"><Button variant="secondary" onClick={()=>navigate(`/app/${workspace}/quotations/${item.id}`)}>View Quotation</Button><Button variant="secondary" onClick={()=>downloadQuotation(item.id,item.number).catch(reason=>setNotice({kind:'error',text:reason.message}))}>Download Quotation</Button></div></td></tr>)}</tbody></table></CommercialCard>}

    {tab==='orders'&&<CommercialCard title="Orders" empty={!data.orders.length?{text:latestQuote?.status==='ACCEPTED'?'The accepted quotation is ready to convert into an order.':'An order can be created after the quotation is accepted.',action:<div className="button-row">{latestQuote&&<Button variant="secondary" onClick={()=>navigate(`/app/${workspace}/quotations/${latestQuote.id}`)}>View Quotation</Button>}{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&latestQuote?.status==='ACCEPTED'&&<Button onClick={async()=>{const result=await mutate('order',`/api/v1/quotations/${latestQuote.id}/order`,'Order created.','Convert this accepted quotation to an order?');if(result?.id)navigate(`/app/${workspace}/orders/${result.id}`)}}>Convert Accepted Quotation to Order</Button>}</div>}:undefined}><table><thead><tr><th>Order</th><th>Quotation</th><th>Building scope</th><th>Date</th><th>Delivery</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>{data.orders.map(item=><tr key={item.id}><td>{item.number}</td><td>{data.quotations.find(x=>x.id===item.quotation_id)?.number||'—'}</td><td>{scope(item.building_id)}</td><td>{item.order_date}</td><td>{item.delivery_date||'—'}</td><td><Status value={item.status}/></td><td>{money(item.grand_total)}</td><td><div className="button-row"><Button variant="secondary" onClick={()=>navigate(`/app/${workspace}/orders/${item.id}`)}>View</Button>{(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&!data.invoices.some(x=>x.order_id===item.id)&&<Button onClick={()=>mutate(`invoice-${item.id}`,`/api/v1/orders/${item.id}/invoice`,'Invoice generated.','Generate an invoice from this order?')}>Generate Invoice</Button>}</div></td></tr>)}</tbody></table></CommercialCard>}

    {tab==='invoices'&&<CommercialCard title="Invoices" empty={!data.invoices.length?{text:latestOrder?'The order is ready for invoice generation.':'An invoice can be generated after an order is created.',action:(user?.role==='ADMIN'||user?.role==='SUPER_ADMIN')&&latestOrder?<Button onClick={async()=>{const result=await mutate('invoice',`/api/v1/orders/${latestOrder.id}/invoice`,'Invoice generated.','Generate an invoice from this order?');if(result?.id)navigate(`/app/${workspace}/invoices/${result.id}`)}}>Generate Invoice</Button>:undefined}:undefined}><table><thead><tr><th>Invoice</th><th>Order</th><th>Building scope</th><th>Invoice date</th><th>Due date</th><th>Payment status</th><th>Total</th><th>Paid</th><th>Balance</th><th>Action</th></tr></thead><tbody>{data.invoices.map(item=><tr key={item.id}><td>{item.number}</td><td>{item.order_number}</td><td>{scope(item.building_id)}</td><td>{item.invoice_date}</td><td>{item.due_date||'—'}</td><td><Status value={item.status}/></td><td>{money(item.grand_total)}</td><td>{money(item.paid_total)}</td><td>{money(item.balance_due)}</td><td><div className="button-row"><Button variant="secondary" onClick={()=>navigate(`/app/${workspace}/invoices/${item.id}`)}>View Invoice</Button><Button variant="secondary" onClick={()=>downloadInvoice(item.id,item.number).catch(reason=>setNotice({kind:'error',text:reason.message}))}>Download Invoice</Button></div></td></tr>)}</tbody></table></CommercialCard>}

    {tab==='documents'&&<div className="download-grid"><DownloadCard title="Project Book" text="Complete project, physical structure, BOQ and commercial lineage." preview={()=>runFile('project-preview',`/api/v1/projects/${id}/book.pdf`,'preview')} download={()=>runFile('project-download',`/api/v1/projects/${id}/book.pdf?download=true`,'download')}/>{data.buildings.map(building=><DownloadCard key={building.id} title={`${building.name} Building Book`} text="Building, floor, room, board and product configuration." preview={()=>runFile(`preview-${building.id}`,`/api/v1/projects/${id}/buildings/${building.id}/book.pdf`,'preview')} download={()=>runFile(`download-${building.id}`,`/api/v1/projects/${id}/buildings/${building.id}/book.pdf?download=true`,'download')} excel={()=>runFile(`excel-${building.id}`,`/api/v1/projects/${id}/buildings/${building.id}/boq.xlsx`,'download')}/>)}</div>}

    <Modal open={userModal} title="Project Access" onClose={()=>setUserModal(false)} footer={<><Button variant="secondary" onClick={()=>setUserModal(false)}>Close</Button><Button disabled={!form.name||!form.email||busy==='user'} onClick={addUser}>{busy==='user'?'Assigning…':'Create & Assign'}</Button></>}><p className="muted">Access applies to this project and all its buildings. New users receive a one-time temporary password.</p><div className="form-grid two"><label>Name *<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Email *<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Phone<input value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></label></div>{data.users.length>0&&<div className="access-list">{data.users.map(item=><div key={item.id}><span><b>{item.user.name}</b><small>{item.user.email} · {item.status}</small></span><Button variant="danger" onClick={()=>setRemoveUser(item)}><Trash2 size={14}/></Button></div>)}</div>}</Modal>
    <Modal open={Boolean(removeUser)} title="Remove user from project?" onClose={()=>setRemoveUser(undefined)} footer={<><Button variant="secondary" onClick={()=>setRemoveUser(undefined)}>Cancel</Button><Button variant="danger" disabled={busy==='remove'} onClick={remove}>{busy==='remove'?'Removing…':'Remove'}</Button></>}><p><b>{removeUser?.user.name}</b> will lose access to this project and its records.</p></Modal>
  </>
}

function CommercialCard({title,empty,children}:{title:string;empty?:{text:string;action?:ReactNode};children:ReactNode}){return <Card className="table-card"><div className="section-head"><div><h2>{title}</h2><p>Records are scoped to this project.</p></div></div>{empty?<Empty text={empty.text} action={empty.action}/>:<div className="table-wrap">{children}</div>}</Card>}
function ProjectBoqRow({row,showPrices,open,toggle}:{row:BOQRow;showPrices:boolean;open:boolean;toggle:()=>void}){return <><tr><td><button className="icon-button" aria-label={`${open?'Collapse':'Expand'} ${row.name}`} onClick={toggle}>{open?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</button></td><td><b>{row.name}</b></td><td>{row.sku}</td><td><Status value={row.workspace}/></td><td>{row.category}</td><td>{row.unit}</td>{showPrices&&<><td>{money(row.rate)}</td><td>{row.tax_rate||0}%</td></>}<td>{row.quantity}</td></tr>{open&&<tr className="boq-breakdown-row"><td></td><td colSpan={showPrices?8:6}><div className="boq-breakdown">{row.breakdown.map((item,index)=><span key={`${item.building}-${item.floor}-${item.room}-${index}`}><b>{item.building}</b> / {item.floor} / {item.room}<strong>{item.quantity} {row.unit}</strong></span>)}</div></td></tr>}</>}
function DownloadCard({title,text,preview,download,excel}:{title:string;text:string;preview:()=>void;download:()=>void;excel?:()=>void}){return <Card className="download-card"><span className="download-card-icon"><Download size={22}/></span><h3>{title}</h3><p>{text}</p><div className="button-row"><Button variant="secondary" onClick={preview}><Eye size={15}/> Preview</Button>{excel&&<Button variant="secondary" onClick={excel}><FileSpreadsheet size={15}/> BOQ Excel</Button>}<Button onClick={download}><Download size={15}/> Download</Button></div></Card>}
