import {useEffect,useMemo,useState} from 'react'
import {Minus,Plus,Send,ShoppingCart} from 'lucide-react'
import {useParams} from 'react-router-dom'
import {api,post} from '../api/client'
import {Button,Card,Empty,Notice,PageTitle,ProductImage} from '../components/UI'
import type {BuildingDetail,Product,ProjectBuilding,ProjectSummary} from '../types'

type CartRow={product:Product;roomId:string;quantity:number;notes:string}

export default function RequestProductsPage(){
  const {workspace='lighting'}=useParams()
  const [projects,setProjects]=useState<ProjectSummary[]>([]),[products,setProducts]=useState<Product[]>([])
  const [projectId,setProjectId]=useState(''),[buildings,setBuildings]=useState<ProjectBuilding[]>([]),[buildingId,setBuildingId]=useState('')
  const [detail,setDetail]=useState<BuildingDetail>(),[cart,setCart]=useState<CartRow[]>([]),[notice,setNotice]=useState<{kind:'success'|'error';text:string}>(),[busy,setBusy]=useState(false)
  useEffect(()=>{Promise.all([api<ProjectSummary[]>(`/api/v1/projects?workspace=${workspace.toUpperCase()}`),api<Product[]>(`/api/v1/products?workspace=${workspace.toUpperCase()}`)]).then(([p,v])=>{setProjects(p);setProducts(v);if(p.length)setProjectId(p[0].id)}).catch(e=>setNotice({kind:'error',text:e.message}))},[workspace])
  useEffect(()=>{if(!projectId)return;api<ProjectBuilding[]>(`/api/v1/projects/${projectId}/buildings`).then(rows=>{setBuildings(rows);setBuildingId(rows[0]?.id||'')})},[projectId])
  useEffect(()=>{if(!projectId||!buildingId){setDetail(undefined);return}api<BuildingDetail>(`/api/v1/projects/${projectId}/buildings/${buildingId}`).then(setDetail)},[projectId,buildingId])
  const rooms=useMemo(()=>detail?.floors.flatMap(f=>f.rooms.map(r=>({...r,label:`${f.name} · ${r.name}`})))||[],[detail])
  const add=(product:Product)=>setCart(rows=>rows.some(x=>x.product.id===product.id)?rows.map(x=>x.product.id===product.id?{...x,quantity:x.quantity+1}:x):[...rows,{product,roomId:rooms[0]?.id||'',quantity:1,notes:''}])
  const submit=async()=>{if(!projectId||!cart.length||cart.some(x=>!x.roomId)){setNotice({kind:'error',text:'Select a project room for every product.'});return}setBusy(true);try{const created=await post<any>('/api/v1/product-requests',{project_id:projectId,items:cart.map(x=>({product_id:x.product.id,room_id:x.roomId,quantity:x.quantity,notes:x.notes||undefined})),notes:'Submitted from My Requests'});setCart([]);setNotice({kind:'success',text:`Request ${created.number} submitted for review.`})}catch(e:any){setNotice({kind:'error',text:e.message})}finally{setBusy(false)}}
  return <><PageTitle title="Request Products" subtitle="Choose exact variants and assign every requested quantity to a project room" badge="Project User" actions={<Button disabled={busy||!cart.length} onClick={submit}><Send size={16}/> Submit request ({cart.length})</Button>}/>{notice&&<Notice kind={notice.kind}>{notice.text}</Notice>}<Card><div className="form-grid two"><label>Project<select value={projectId} onChange={e=>{setProjectId(e.target.value);setCart([])}}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Building<select value={buildingId} onChange={e=>{setBuildingId(e.target.value);setCart([])}}>{buildings.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label></div></Card><div className="request-shop-grid"><Card><h2>Product catalogue</h2>{!products.length?<Empty text="No active products are available."/>:<div className="room-product-grid">{products.map(product=><article className="room-product-card" key={product.id}><ProductImage product={product} size={80}/><div className="room-product-copy"><h3>{product.name}</h3><p>{product.variant_name||product.sku}</p><small>{product.category} · {product.available} {product.unit} available</small></div><Button onClick={()=>add(product)}><Plus size={15}/> Add</Button></article>)}</div>}</Card><Card><h2><ShoppingCart size={20}/> Request cart</h2>{!cart.length?<Empty text="Add products to begin a room-scoped request."/>:<div className="compact-list">{cart.map(row=><div key={row.product.id}><span><b>{row.product.name}</b><small>{row.product.sku}</small><select value={row.roomId} onChange={e=>setCart(values=>values.map(x=>x.product.id===row.product.id?{...x,roomId:e.target.value}:x))}><option value="">Select room</option>{rooms.map(room=><option value={room.id} key={room.id}>{room.label}</option>)}</select></span><span className="button-row"><Button variant="secondary" onClick={()=>setCart(values=>values.map(x=>x.product.id===row.product.id?{...x,quantity:Math.max(1,x.quantity-1)}:x))}><Minus size={14}/></Button><b>{row.quantity}</b><Button variant="secondary" onClick={()=>setCart(values=>values.map(x=>x.product.id===row.product.id?{...x,quantity:x.quantity+1}:x))}><Plus size={14}/></Button></span></div>)}</div>}</Card></div></>
}
