export type Workspace='LIGHTING'|'AUTOMATION'

export type UserRole='SUPER_ADMIN'|'ADMIN'|'SALES_MANAGER'|'SALES_EXECUTIVE'|'DESIGNER'|'ENGINEER'|'ACCOUNTS'|'WAREHOUSE'|'DISPATCH'|'SERVICE'|'RMA'|'PARTNER_ADMIN'|'PARTNER_USER'|'USER'
export interface User {id:string;name:string;email:string;phone?:string|null;role:UserRole;status:string;workspaces:Workspace[];permissions:string[];must_change_password?:boolean;last_login?:string|null;partner_id?:string|null}
export interface Customer {id:string;company_name:string;contact_person?:string|null;email?:string|null;phone?:string|null;gstin?:string|null;address?:string|null;city?:string|null;state?:string|null;status:string;created_at?:string|null;updated_at?:string|null;project_count?:number;active_project_count?:number;last_activity?:string|null}
export interface Partner {id?:string;business_name:string;mobile:string;email:string;address:string;created_at?:string}

export interface ProductMedia {id:string;url:string;media_type:string;alt_text:string;caption?:string|null;sort_order:number;is_primary:boolean;width?:number|null;height?:number|null}
export interface Product {
  id:string;family_id?:string|null;family_name?:string;variant_name?:string|null;model_number?:string|null;workspace:Workspace;category_id:string;category:string;sku:string;name:string;internal_name?:string|null;description?:string|null;full_description?:string|null;brand:string;manufacturer?:string|null;barcode?:string|null;search_tags?:string[];status:string;
  on_hand?:number;reserved?:number;available:number;reorder_level?:number;unit:string;price?:number;cost?:number|null;mrp_price?:number|null;project_price?:number|null;dealer_price?:number|null;reseller_price?:number|null;currency?:string;minimum_order_quantity?:number;pricing_status?:string;tax_rate:number;hsn_sac?:string|null;specs:Record<string,string|number|boolean>;
  images:string[];media?:ProductMedia[];primary_image_url?:string|null;highlights?:string[];features?:string[];applications?:string[];installation_summary?:string|null;care_guide?:string|null;warranty_summary?:string|null;internal_notes?:string|null;lead_time_days?:number|null;warranty?:string|null;
  stock_status:'IN_STOCK'|'LOW_STOCK'|'OUT_OF_STOCK';movements?:Array<{id:string;type:string;quantity:number;reason?:string;created_at:string}>
}
export interface ProductFamily {id:string;workspace:Workspace;category_id:string;category:string;name:string;slug:string;brand:string;short_description?:string|null;full_description?:string|null;suitability_guidance?:string|null;features:string[];applications:string[];status:string;variant_count:number;available:number;availability:'IN_STOCK'|'OUT_OF_STOCK';starting_price?:number;primary_image_url?:string|null;media:ProductMedia[];variants?:Product[];created_at?:string|null;updated_at?:string|null}
export interface PaginatedFamilies {items:ProductFamily[];page:number;page_size:number;total:number;pages:number;brands:string[]}

export interface Requirement {id?:string;product:Product;quantity:number;unit:string;notes?:string|null;inquiry_id?:string|null;approval_status?:string;source?:string}
export interface ProjectRoom {id:string;name:string;room_type?:string|null;area?:number|null;occupancy?:number|null;notes?:string|null;requirements:Requirement[];product_quantity:number;unique_product_count?:number;main_board_count?:number;configuration_status?:string;product_thumbnails?:string[]}
export interface ProjectFloor {id:string;name:string;sort_order?:number;rooms:ProjectRoom[];room_count:number;product_quantity:number;unique_product_count?:number;main_board_count?:number;configuration_status?:string}
export interface ProjectBuilding {id:string;project_id?:string;name:string;code?:string|null;building_type?:string|null;address?:string|null;status?:string;floors:ProjectFloor[];floor_count:number;room_count?:number;main_board_count?:number;unique_product_count?:number;product_quantity?:number}
export interface ProjectSummary {id:string;customer_id?:string;name:string;city?:string|null;state?:string|null;address?:string|null;status:string;workspaces:Workspace[];customer?:Customer;partner?:Partner|null;owner?:{id:string;name:string}|null;expected_completion?:string|null;buildings?:number;created_at?:string|null;updated_at?:string|null}
export interface ProjectUser {id:string;project_id:string;user_id:string;role:string;status:string;permissions:string[];created_at:string;user:User;temporary_password?:string}
export interface Activity {id:string;actor:string;action:string;entity_type?:string;entity_id?:string|null;metadata?:Record<string,unknown>;created_at:string}

export interface BOQRow {product_id:string;sku:string;name:string;category:string;workspace:Workspace;unit:string;quantity:number;rate?:number;tax_rate?:number;specs:Record<string,string|number|boolean>;breakdown:Array<{building:string;floor:string;room:string;quantity:number;notes?:string|null}>}
export interface QuotationItem {id:string;product_id:string;description:string;sku:string;qty:number;rate?:number;tax_rate:number;amount?:number}
export interface Inquiry {id:string;number:string;customer:Customer;project:ProjectSummary;building_id?:string|null;building_name?:string|null;is_project_wide?:boolean;workspace:Workspace;workspace_scope:Workspace[];owner:{id:string;name:string};status:string;source:string;wizard_step:number;notes?:string|null;estimated_value:number;submitted_at?:string|null;created_at:string;updated_at:string;structure?:ProjectBuilding[];boq?:BOQRow[];partner?:Partner|null;quotation?:Quotation|null;activity?:Activity[]}
export interface Quotation {id:string;number:string;inquiry_id:string;building_id?:string|null;customer:Customer;project:ProjectSummary;workspace:Workspace;status:string;quotation_date:string;valid_until?:string;payment_terms:string;delivery_terms?:string|null;warranty_terms?:string|null;notes?:string|null;revision?:number;discount_percent:number;subtotal:number;discount_amount:number;tax_total:number;grand_total:number;items?:QuotationItem[]}
export interface Order {id:string;number:string;quotation_id:string;building_id?:string|null;customer:Customer;project:ProjectSummary;workspace:Workspace;status:string;order_date:string;delivery_date?:string;delivery_address?:string|null;dispatch_reference?:string|null;dispatched_at?:string|null;subtotal?:number;tax_total?:number;grand_total?:number;items?:QuotationItem[]}
export interface InvoiceItem {description:string;sku:string;hsn_sac?:string|null;qty:number;unit:string;rate?:number;tax_rate:number;amount?:number}
export interface Invoice {id:string;number:string;order_id:string;order_number:string;building_id?:string|null;customer:Customer;project?:ProjectSummary|null;workspace:Workspace;status:string;invoice_date:string;due_date?:string;place_of_supply?:string|null;subtotal?:number;cgst?:number;sgst?:number;igst?:number;round_off?:number;grand_total?:number;amount_in_words?:string;company?:Record<string,string|null>;bank?:Record<string,string|null>;payments?:Array<{id:string;amount:number;method:string;reference?:string|null;paid_at:string}>;paid_total?:number;balance_due?:number;items:InvoiceItem[]}
export interface ProjectDetail {project:ProjectSummary;customer:Customer;partner?:Partner|null;stats:{buildings?:number;floors:number;rooms:number;main_boards?:number;users:number;products:number;unique_products?:number};buildings:ProjectBuilding[];users:ProjectUser[];inquiries:Inquiry[];quotations:Quotation[];orders:Order[];invoices:Invoice[];activity?:Activity[]}

export interface MainBoard {id:string;project_id:string;building_id:string;floor_id:string;room_id?:string|null;name:string;code?:string|null;board_type:string;system:string;quantity:number;notes?:string|null}
export interface RoomProduct {id:string;project_id:string;building_id:string;floor_id:string;room_id:string;product:Product;quantity:number;unit:string;notes?:string|null;approval_status:string;source:string;linked_inquiry_id?:string|null}
export interface ProductProposal {id:string;product:Product;quantity:number;unit:string;notes?:string|null;recommendation?:string|null;customer_comment?:string|null;status:string;proposed_at:string;sent_at?:string|null;decided_at?:string|null}
export interface RoomDetail {customer:Customer;project:ProjectSummary;building:{id:string;name:string};floor:{id:string;name:string};room:{id:string;name:string;room_type?:string|null;area?:number|null;occupancy?:number|null;notes?:string|null;configuration_status:string};products:RoomProduct[];main_boards:MainBoard[];proposals:ProductProposal[]}
export interface BuildingDetail {customer:Customer;project:ProjectSummary&{partner?:Partner|null;owner?:{id:string;name:string}|null};building:{id:string;project_id:string;name:string;code?:string|null;building_type?:string|null;address?:string|null;status:string;planned_floors:number;created_at?:string|null;updated_at?:string|null};stats:{floors:number;rooms:number;main_boards:number;unique_products:number;product_quantity:number;users:number;open_inquiries:number;active_quotation?:string|null;order_status?:string|null;invoice_status?:string|null;outstanding:number};floors:Array<{id:string;name:string;sort_order:number;room_count:number;main_board_count:number;unique_product_count:number;product_quantity:number;configuration_status:string;rooms:Array<Omit<ProjectRoom,'requirements'>>}>;main_boards:MainBoard[];inquiries:Array<{id:string;number:string;status:string;created_at:string;building_scope:string}>;quotations:Quotation[];orders:Order[];invoices:Invoice[]}
export interface SearchResult {type:'product'|'product_family'|'customer'|'project'|'building'|'room'|'inquiry'|'quotation'|'order'|'invoice';id:string;variant_id?:string;customer_id?:string;project_id?:string;building_id?:string;floor_id?:string;label:string;sub?:string|null;workspace?:Workspace}
